version: '3.3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: redcontrol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redcontrol
    volumes:
      - /var/lib/postgresql/data
